---
title: "Getting Started in R"
date: 2020-06-01
output:
  blogdown::html_page:
    section_divs: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

Our goal in learning R is to introduce you to some skills in exploring oceanographic data in R. This will mainly involve plotting tools, but will also include some discussion of working with data sets.

NOTE: There is no exercise submission or Peer Discussion requirements for this work, but please reach out on the course Slack channel if you have any technical issues.

# Why R?

Perhaps the best place to start is to ask ourselves why we are choosing to use R. Fortunately, Rob Schlegel (WHOI) sums up nicely why using R is a good idea for data science as part of his R workshop. Please read [this](https://robwschlegel.github.io/Intro_R_Workshop/prelim.html#why-use-r).

Dan Kelley (Dalhousie) has a nice book on oceanographic analysis in R - his sub-chapter on ["Why R, and Why Now?"](/docs/Kelley_whyR.pdf) is a quick read to help contextualize the desire to use R for oceanographic work.

Please read both these short justifications to give you an insight into why R is something worth your energy.

# Downloading R and RStudio

You should next download both R (the programming language) and Rstudio (a nice visual interface that makes writing code more intuitive) and open RStudio to see that it has worked properly.

You need to download R first:

* Go to http://www.r-project.org/ and choose "download R" under "Getting Started".
* Select any of the sites to download R from
* Choose the R link for your operating system
* **Windows**: select "base" and then "Download R for Windows". Run the .exe file that you download to install R
* **Mac**: select the .pkg link to download. Run the file that you download to install.

Then you need to download RStudio:

* Go to http://www.rstudio.com
* Click "Download RStudio" and following the instructions for your operating system.

To use R you need to open RStudio (not the R link that might have appeared on your desktop).

# Intro to R

If you've never used R or RStudio before it's worth a little bit of orientation.

You can get some basics on how to use R from [this tutorial](https://rstudio.cloud/learn/primers/1.2). Watch the videos and run the interactive code chunks to learn some of the basics.

Watch this video to orient yourself to the RStudio Interface

<iframe width="560" height="315" src="https://www.youtube.com/embed/cnQ-v1UUWyE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



