---
title: Introduction
output:
  blogdown::html_page:
    section_divs: no
---

## Course Goals

During the course we have two main goals:

1. Develop student understanding of topics in ocean and environmental science pertinent to global climate change with a focus on activities in the Woods Hole science community.
1. Build student research skills to aid their summer internship work and future careers.

The first goal will be achieved through a series of classes on basic oceanography spanning physics, chemistry and biology. These classes will be supplemented with more advanced topics, introduced by leading researchers in the Woods Hole community, that will bring students' understanding to the frontier of current understanding.

The second goal will be achieved through working on mini-projects centered on data collected on two previous PEP cruises out of Woods Hole. Students will work in teams to build on the introductory class in oceanography to develop their understanding of a particular focus area. To do this, students will need to develop capacity in finding and reading scientific literature, creating hypotheses, visualizing geospatial data, summarizing results, collaborating as a team, and creating a professional research poster. The development of these skills will serve as a primer for the internship research work students will conduct over the course of the rest of the summer.

The individual classes of the course will therefore fall into one of three categories:

1. Introduction to Oceanography (4 classes): Exposure and review of key topics in oceanography
1. Advanced Topics (6 classes): Researcher-led presentation and discussion of frontier topics in Woods Hole community.
1. Research skills (8 classes): e.g. How to read literature, how to find and organize literature, visualization tools, poster development, etc.

## Format

This being an remote offering, the format might be a little different to many in-person class. The onus will be on *you* to read and grapple with the content and skills independently and with your peers at first before a full class discussion, review and extension of the material.

Expect the steps in the daily routine to follow this basic pattern:

**Independent Work**: This will be work that you conduct individually and should take you somewhere between 1 and 2 hours to complete. You may be asked to do some reading, apply your knowledge, conduct some background research or reflect on a topic. Most days will involve submitting answers at the end of the work to allow us to keep track of what you have been doing, but other than completing the work in a timely manner, this work is ungraded.

**Team Work**: After the initial independent work, you will be assigned a study team and a selection of questions or activities for you to work through together on a video call. This could include reviewing independent exercises, discussing an advanced questions, or compiling a presentation for class. This is likely to take about 30 mins and no longer than one hour. You will be asked to submit a response or series of open questions at the end of this conference, or have something to present in class.

**Class Discussion**: After you have all completed your individual and team work, we will meet as a full cohort to review the content or skills and advance the conversation. This may involve students asking clarifying questions, student presentations, instructor presentations, breakout groups or other discussion items. We will also provide a preview of the next section of classwork. This will take an hour or more.

**The total amount of hours you are expected to spend on the course (including the video class) is 3-4 hours**. This does not include time spent in other PEP professional development or social activities, nor does it include time spent spinning-up your internship research project with your mentor. If you find yourself spending significantly more time than this, please let us know as soon as possible.

## Platforms

To deliver the class content and skills, we will be using the following platforms:

### Class Site

The site you are reading this on is the class website. It will be where we share class content and exercises. Every day's class will be explained on here including your independent and team work expected ahead of the class. If a submission is required I will link directly to it in Google Classroom (see below).

The classes are organized into the order of the day of the class discussions. That said, there is likely to be work on some chapters that you will need to conduct a few days in advance of the class discussion so read ahead and be tuned into what you instructors are telling you.

### Google Classroom

Google Classroom will be where we organize assignments and submissions for various component of the course. This will include both participatory submissions (i.e. ungraded for content) and graded submissions. Instructions for graded submissions will be provided on Google Classroom and may not also be covered on the Class Site.

To sign-up for the PEP 2020 Class on Google Classroom, follow the instructions on the course Slack channel.

### Zoom and Google Hangouts

We will be using Zoom for classes (and other PEP business) and Google Hangouts for team discussions.

The Zoom meetings are scheduled and available in the PEP Calendar. There is also a link to the meetings on Google Classroom.

We recommend you organize your Team discussion in Google Hangouts, which you can add directly to Slack, but you can also organize to talk via another means as you prefer.

### Slack

To facilitate direct communication with and between members of the 2020 PEP Cohort, we will be using Slack. This is a direct and group messaging application that will allow us to share news and upcoming events with the whole group as well as organize smaller discussions or contact individual students.

You will also be asked to report back from your peer discussion in the peer_discussion Slack channel.

### Google Drive

You will have also received an email about a Google Drive folder that has been set up for you at SEA. Please feel free to use this to store any work related items that you need in one place or want to share with others. This is also a good place to also back-up your work - remember to back up your work to the cloud or an external hard drive!

## Resources

Our general oceanography text will be:

[Introduction to Ocean Sciences](https://www.reefimages.com/oceansci.php), Second digital edition, ver 4.14 by Douglas A. Segar

This is a good introductory text on the many aspects of ocean science and is all [available online](https://www.reefimages.com/oceansci.php) for free. We'll be directing you to readings by chapter number and page. In addition, there is a section called [Critical Concepts](https://www.reefimages.com/oceans/SegarOcean4CritCon.pdf) which covers ideas that span multiple chapters. We will be directing you to review some of those by number also. The chapters all load as PDFs so you might consider saving assigned chapters to your computer and organizing them for future browsing.

For R visualization work, the core text is:

[R for Data Science](https://r4ds.had.co.nz/) by Garrett Grolemund and Hadley Wickham. This is a great intro text to working with data in R. I recommend reading the whole thing over the course of the summer, but I'll be assigning specific chapters in class.

We're compiling additional R resources on [this page](/r_resources) too.

In addition to the R text and resources, we have a dedicated Slack channel for R questions (and a cohort of PEP alums to answer them) and Luis Valentin as a computational adviser who will have office hours available.

Other readings and resources for the class will be distributed as required. 